name: Fetch latest SemVer tag

on:
  workflow_call:

jobs:
  fetch-tag:
    runs-on: ubuntu-latest

    outputs:
      latest_tag: ${{ steps.get_tag.outputs.latest_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get the latest SemVer tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag is $LATEST_TAG"
          echo "::set-output name=latest_tag::$LATEST_TAG"
